project/urls.py
from django.contrib import admin
from django.urls import path
from app_dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
    path('fornecedores/', views.fornecedores, name='fornecedores'),
    path('fornecedores/adicionar/', views.adicionar_fornecedor, name='adicionar_fornecedor'),
    path('fornecedores/editar/<fornecedor_id>/', views.editar_fornecedor, name='editar_fornecedor'),
    path('fornecedores/deletar/<fornecedor_id>/', views.deletar_fornecedor, name='deletar_fornecedor'),

    path('clientes/', views.clientes, name='clientes'),
    path('clientes/adicionar/', views.adicionar_clientes, name='adicionar_clientes'),
    path('clientes/editar/<cliente_id>/', views.editar_clientes, name='editar_clientes'),
    path('clientes/deletar/<cliente_id>/', views.deletar_clientes, name='deletar_clientes'),

    path('usuarios/', views.usuarios, name='usuarios'),
    path('usuarios/adicionar/', views.adicionar_usuario, name='adicionar_user'),
    path('usuarios/editar/<user_id>/', views.editar_usuario, name='editar_user'),
    path('usuarios/alterar-senha/<user_id>/', views.editar_senha_usuario, name='alterar_senha_user'),
    path('usuarios/deletar/<user_id>/', views.deletar_usuario, name='deletar_user'),

    path('pagamentos/', views.pagamentos, name='pagamentos'),
    path('pagamentos/adicionar', views.adicionar_pagamento, name='adicionar_pagamento'),
    path('pagamentos/editar/<pagamento_id>/', views.editar_pagamento, name='editar_pagamento'),
    path('pagamentos/deletar/<pagamento_id>/', views.deletar_pagamento, name='deletar_pagamento'),
    path('duplicar_pagamento/<int:pagamento_id>/', views.duplicar_pagamento, name='duplicar_pagamento'),

    path('recebimentos/', views.recebimentos, name='recebimentos'),
    path('recebimentos/adicionar', views.adicionar_recebimento, name='adicionar_recebimento'),
    path('recebimentos/editar/<recebimento_id>/', views.editar_recebimento, name='editar_recebimento'),
    path('recebimento/deletar/<recebimento_id>/', views.deletar_recebimento, name='deletar_recebimento'),
    path('duplicar_recebimento/<int:recebimento_id>/', views.duplicar_recebimento, name='duplicar_recebimento'),

    path('atualizar-vencimentos/', views.atualizar_vencimentos, name='atualizar_vencimentos'),
    path('404/', views.superuser_or_staff_required, name='404'),
    path('criar-loja/', views.criar_loja, name='criar_loja'),
    path('excluir-loja/<int:loja_id>/', views.excluir_loja, name='excluir_loja'),
    path('centro-custo/', views.centro_custo_view, name='centro_custo'),
    path('centro-custo/excluir/<int:centro_id>/', views.excluir_centro_custo, name='excluir_centro_custo'),
]

app_dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

RECEBIMENTO_STATUS = [
    ('pendente', 'Pendente'),
    ('pago', 'Pago'),
    ('vencido', 'Vencido'),
]

PAGAMENTO_STATUS = [
    ('pendente', 'Pendente'),
    ('pago', 'Pago'),
    ('vencido', 'Vencido'),
]

LOJA_CHOICES = [
        ('BARBACOA', 'Barbacoa'),
        ('BARRA', 'Barra'),
        ('VILAS', 'Vilas'),
        ('SMART', 'Smart'),
        ('DIGITAL', 'Digital'),
        ('APP', 'App'),
]

CENTRO_CUSTO_CHOICES = [
    ('Antecipação', 'Antecipação'),
    ('Bonificação', 'Bonificação'),
    ('Campanha', 'Campanha'),
    ('Comemoração', 'Comemoração'),
    ('Comissão', 'Comissão'),
    ('Diferido', 'Diferido'),
    ('Empréstimos', 'Empréstimos'),
    ('Equipamento', 'Equipamento'),
    ('Extra', 'Extra'),
    ('Folha de Pagamento', 'Folha de Pagamento'),
    ('Imposto', 'Imposto'),
    ('Investimentos', 'Investimentos'),
    ('Locação', 'Locação'),
    ('Manutenção', 'Manutenção'),
    ('Participação dos Lucros', 'Participação dos Lucros'),
    ('Sistema', 'Sistema'),
    ('Tarifa', 'Tarifa'),
]


class CentroCusto(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def clean(self):
        # Validar se o nome está em CENTRO_CUSTO_CHOICES
        if self.nome.upper() not in dict(CENTRO_CUSTO_CHOICES).keys():
            # Adicione validação adicional se necessário
            pass

    def save(self, *args, **kwargs):
        # Formatar o nome: Primeira letra maiúscula e demais minúsculas
        self.nome = self.nome.capitalize().strip()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Loja(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def clean(self):
        # Validar se o nome está em LOJA_CHOICES
        if self.nome.upper() not in dict(LOJA_CHOICES).keys():
            # Adicione validação adicional se necessário
            pass

    def save(self, *args, **kwargs):
        # Formatar o nome: Primeira letra maiúscula e demais minúsculas
        self.nome = self.nome.capitalize().strip()
        # Remover caracteres especiais e acentos
        self.nome = self.nome.replace('ç', 'c')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome
    
class UsuarioPerfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    lojas = models.ManyToManyField(Loja, blank=True, related_name='usuarios')

    def __str__(self):
        return self.user.username

class Fornecedor(models.Model):
    nome = models.CharField(max_length=120, verbose_name='Nome')
    telefone = models.CharField(max_length=20, verbose_name='Telefone')
    documento = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
    rua = models.CharField(max_length=250, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, verbose_name='Número')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')
    loja = models.CharField(max_length=10, choices=LOJA_CHOICES, default='BARBACOA', verbose_name='Loja')
    # centro_custo = models.CharField(max_length=50, choices=CENTRO_CUSTO_CHOICES, default='', verbose_name='Centro de Custo')

    def __str__(self):
        return self.nome


class Cliente(models.Model):
    nome = models.CharField(max_length=120, verbose_name='Nome')
    telefone = models.CharField(max_length=20, verbose_name='Telefone')
    documento = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
    rua = models.CharField(max_length=250, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, verbose_name='Número')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')
    loja = models.CharField(max_length=10, choices=LOJA_CHOICES, default='BARBACOA', verbose_name='Loja')
    # centro_custo = models.CharField(max_length=50, choices=CENTRO_CUSTO_CHOICES, default='', verbose_name='Centro de Custo')

    def __str__(self):
        return self.nome


class Recebimento(models.Model):
    STATUS_CHOICES = [
        ('PAGO', 'Pago'),
        ('PENDENTE', 'Pendente'),
        ('VENCIDO', 'Vencido'),
    ]

    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')
    data_emissao = models.DateField(auto_now_add=True, verbose_name='Data de Emissão')
    data_vencimento = models.DateField(verbose_name='Data de Vencimento')
    status = models.CharField(max_length=30, choices=RECEBIMENTO_STATUS, default='pendente')
    loja = models.CharField(max_length=10, choices=LOJA_CHOICES, default='BARBACOA', verbose_name='Loja')
    centro_custo = models.CharField(max_length=50, choices=CENTRO_CUSTO_CHOICES, default='', verbose_name='Centro de Custo')
    data_recebimento = models.DateField(verbose_name='Data de Recebimento', null=True, blank=True)

    def __str__(self):
        return self.descricao
    
    class Meta:
        ordering = ['-data_emissao']  # Ordena por data de recebimento em ordem decrescente


class Pagamento(models.Model):
    STATUS_CHOICES = [
        ('PAGO', 'Pago'),
        ('PENDENTE', 'Pendente'),
        ('VENCIDO', 'Vencido'),
    ]

    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.SET_NULL, null=True)
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')
    data_emissao = models.DateField(auto_now_add=True, verbose_name='Data de Emissão')
    data_vencimento = models.DateField(verbose_name='Data de Vencimento')
    status = models.CharField(max_length=30, choices=PAGAMENTO_STATUS, default='pendente')
    loja = models.CharField(max_length=10, choices=LOJA_CHOICES, default='BARBACOA', verbose_name='Loja')
    centro_custo = models.CharField(max_length=50, choices=CENTRO_CUSTO_CHOICES, default='', verbose_name='Centro de Custo')
    data_pagamento = models.DateField(verbose_name='Data de Pagamento', null=True, blank=True)

    def __str__(self):
        return self.descricao
    
    class Meta:
        ordering = ['-data_emissao']

app_dashboard/forms.py
from django import forms
from app_dashboard.models import Fornecedor, Cliente, Recebimento, Pagamento, Loja, UsuarioPerfil, CentroCusto

from django.contrib.auth.models import User

class FornecedorForm(forms.ModelForm):
    
    class Meta:
        model = Fornecedor
        fields = [
            'nome', 
            'telefone', 
            'documento', 
            'rua', 
            'numero', 
            'bairro', 
            'cidade', 
            'estado',
            'loja'
        ]

class EditFornecedorForm(forms.ModelForm):
    
    class Meta:
        model = Fornecedor
        fields = [
            'nome', 
            'telefone', 
            'documento', 
            'rua', 
            'numero', 
            'bairro', 
            'cidade', 
            'estado',
            'loja'
        ]


class UsuarioForm(forms.ModelForm):
    lojas = forms.ModelMultipleChoiceField(
        queryset=Loja.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )
    
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'is_superuser',
            'first_name',
            'last_name',
            'is_staff',
            'is_active'
        ]
        widgets = {
            'password': forms.widgets.PasswordInput
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.set_password(self.cleaned_data['password'])
            user.save()
            perfil, created = UsuarioPerfil.objects.get_or_create(user=user)
            perfil.lojas.set(self.cleaned_data.get('lojas', []))
            perfil.save()
        return user


class EditUsuarioForm(forms.ModelForm):
    lojas = forms.ModelMultipleChoiceField(
        queryset=Loja.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'is_superuser',
            'first_name',
            'last_name',
            'is_staff',
            'is_active'
        ]

    def __init__(self, *args, **kwargs):
        # Passar o perfil do usuário para o formulário
        perfil = kwargs.pop('perfil', None)
        super().__init__(*args, **kwargs)
        if perfil:
            self.fields['lojas'].initial = perfil.lojas.all()

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            perfil, created = UsuarioPerfil.objects.get_or_create(user=user)
            perfil.lojas.set(self.cleaned_data.get('lojas', []))
            perfil.save()
        return user


class clientesForm(forms.ModelForm):
    
    class Meta:
        model = Cliente
        fields = [
            'nome', 
            'telefone', 
            'documento', 
            'rua', 
            'numero', 
            'bairro', 
            'cidade', 
            'estado',
            'loja'
        ]

class EditclientesForm(forms.ModelForm):
    
    class Meta:
        model = Cliente
        fields = [
            'nome', 
            'telefone', 
            'documento', 
            'rua', 
            'numero', 
            'bairro', 
            'cidade', 
            'estado',
            'loja'
        ]


class RecebimentoForm(forms.ModelForm):

    class Meta:
        model = Recebimento
        fields = '__all__'
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'}),
            'data_recebimento': forms.DateInput(attrs={'type': 'date'})
        }


class EditRecebimentoForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label="Selecione um Fornecedor")

    class Meta:
        model = Recebimento
        fields = '__all__'
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'}),
            'data_recebimento': forms.DateInput(attrs={'type': 'date'}),
            'valor': forms.NumberInput(attrs={'step': '0.01'}),  # Configuração para campos decimais
        }

class PagamentoForm(forms.ModelForm):

    class Meta:
        model = Pagamento
        fields = '__all__'
        widgets = {
            # 'loja': forms.Select(choices=[(loja.id, loja.nome) for loja in Loja.objects.all()], attrs={'class': 'form-control'}),
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'}),
            'data_pagamento': forms.DateInput(attrs={'type': 'date'})
        }


class EditPagamentoForm(forms.ModelForm):
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all(), empty_label="Selecione um Fornecedor")

    class Meta:
        model = Pagamento
        fields = '__all__'
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'}),
            'data_pagamento': forms.DateInput(attrs={'type': 'date'}),
            'valor': forms.NumberInput(attrs={'step': '0.01'}),  # Configuração para campos decimais
        }

class LojaForm(forms.ModelForm):
    class Meta:
        model = Loja
        fields = ['nome']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        # Formatar o nome: Primeira letra maiúscula e demais minúsculas
        nome_formatado = nome.capitalize().strip()
        # Remover caracteres especiais e acentos
        nome_formatado = nome_formatado.replace('ç', 'c')
        return nome_formatado
    

class CentroCustoForm(forms.ModelForm):
    class Meta:
        model = CentroCusto
        fields = ['nome']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        # Formatar o nome: Primeira letra maiúscula e demais minúsculas
        nome_formatado = nome.capitalize().strip()
        # Remover caracteres especiais e acentos
        nome_formatado = nome_formatado.replace('ç', 'c')
        return nome_formatado

app_dashboard/templates/pagamentos/adicionar_pagamento.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block conteudo %}
    <a href="{% url 'pagamentos' %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">
                    <span class="fas fa-save"></span>
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock %}

app_dashboard/templates/pagamentos/editar_pagamento.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block conteudo %}
    <a href="{% url 'pagamentos' %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                
                <!-- Exibir mensagens de erro -->
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong>Erro!</strong> Por favor, corrija os erros abaixo.
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ field.label }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                
                <div class="form-group">
                    <label for="id_fornecedor">Fornecedor</label>
                    <select name="fornecedor" id="id_fornecedor" class="form-control">
                        {% for fornecedor in form.fornecedor.field.queryset %}
                            <option value="{{ fornecedor.id }}" {% if fornecedor.id == form.fornecedor.value %}selected{% endif %}>
                                {{ fornecedor.nome }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_descricao">Descrição</label>
                    <input type="text" name="descricao" id="id_descricao" class="form-control" step="0.01" value="{{ form.descricao.value }}">
                </div>
                <div class="form-group">
                    <label for="id_valor">Valor</label>
                    <input type="number" name="valor" id="id_valor" class="form-control" step="0.01" value="{{ form.valor.value|stringformat:'0.2f' }}">
                </div>
                
                <div class="form-group">
                    <label for="id_data_vencimento">Data de Vencimento</label>
                    <input type="date" name="data_vencimento" id="id_data_vencimento" class="form-control" value="{{ form.data_vencimento.value|date:'Y-m-d' }}">
                </div>
                <div class="form-group">
                    <label for="id_status">Status</label>
                    <select name="status" id="id_status" class="form-control">
                        {% for choice in form.fields.status.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.status.value %}selected{% endif %}>
                                {{ choice.1 }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_loja">Loja</label>
                    <select name="loja" id="id_loja" class="form-control">
                        {% for choice in form.fields.loja.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.loja.value %}selected{% endif %}>
                                {{ choice.1 }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_centro_custo">Centro de Custo</label>
                    <select name="centro_custo" id="id_centro_custo" class="form-control">
                        {% for choice in form.fields.centro_custo.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.centro_custo.value %}selected{% endif %}>
                                {{ choice.1 }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_data_pagamento">Data de Pagamento</label>
                    <input type="date" name="data_pagamento" id="id_data_pagamento" class="form-control" value="{{ form.data_pagamento.value|date:'Y-m-d' }}">
                </div>
                <button type="submit" class="btn btn-primary">
                    <span class="fas fa-save"></span>
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock %}